import test from'node:test';import assert from'node:assert/strict';import{Simulation,groundAt,RAMP_END}from'../src/simulation.js';
test('launch reaches air and completes a run',()=>{const sim=new Simulation({});sim.launch();for(let i=0;i<60*30&&sim.state!=='complete';i++)sim.step({right:i%60<20},1/60);assert.equal(sim.state,'complete');assert.ok(sim.result.distance>0);assert.ok(['clean','rough','crash'].includes(sim.result.landing))});
test('air controls rotate in opposite directions',()=>{const left=new Simulation({control:2}),right=new Simulation({control:2});for(const sim of[left,right]){sim.state='air';sim.x=10;sim.y=20;sim.vx=10;sim.vy=0;sim.angle=0;sim.spin=0}left.step({left:true},.1);right.step({right:true},.1);assert.ok(left.angle>0);assert.ok(right.angle<0)});
test('finish is idempotent',()=>{const sim=new Simulation({});sim.finish('stuck');const result=sim.result;sim.finish('bounds');assert.equal(sim.result,result);assert.equal(sim.result.reason,'stuck')});
test('vehicle starts level, waits, then follows the ramp tangent',()=>{const sim=new Simulation({});assert.equal(sim.angle,0);assert.ok(sim.x<-48);sim.launch();for(let i=0;i<120;i++)sim.step({},1/60);assert.equal(sim.state,'starting');assert.equal(sim.x,-64);for(let i=0;i<480&&sim.x<-40;i++)sim.step({},1/60);assert.ok(sim.x>=-48);assert.ok(sim.angle<-.5)});
test('installed parts apply major progression benefits',()=>{const base=new Simulation(),tuned=new Simulation({launch:1,boost:1}),fitted=new Simulation({}, {nose:true,rocketpack:true});assert.equal(tuned.boost,.12);assert.equal(fitted.boost,1.4);base.launch();tuned.launch();fitted.launch();for(let i=0;i<180;i++){base.step({},1/60);tuned.step({},1/60);fitted.step({},1/60)}assert.ok(tuned.vx>base.vx);assert.ok(fitted.vx>tuned.vx)});
test('vehicle generations form an ascending performance ladder',()=>{const ids=['cart','bathtub','coffin','scrapstar'],vehicles=ids.map(id=>new Simulation({}, {},id).vehicle);for(let i=1;i<vehicles.length;i++){assert.ok(vehicles[i].stats.launch>vehicles[i-1].stats.launch);assert.ok(vehicles[i].stats.drag<vehicles[i-1].stats.drag);assert.ok(vehicles[i].stats.tolerance>vehicles[i-1].stats.tolerance)}});
test('each fully upgraded generation has at least twenty percent more range',()=>{const levels={launch:5,aero:5,control:5,durability:5,boost:5},parts={cage:true,nose:true,tailwing:true,rocketpack:true},distances=[];for(const id of['cart','bathtub','coffin','scrapstar']){const sim=new Simulation(levels,parts,id);sim.launch();for(let i=0;i<60*120&&sim.state!=='complete';i++)sim.step({boost:true},1/60);distances.push(sim.result.distance)}for(let i=1;i<distances.length;i++)assert.ok(distances[i]>distances[i-1]*1.2)});
test('ramp facility visibly raises the lip and increases range',()=>{assert.ok(groundAt(RAMP_END-.01,4)>groundAt(RAMP_END-.01,0)+8);const levels={launch:5,aero:5,control:5,durability:5,boost:5},parts={cage:true,nose:true,tailwing:true,rocketpack:true},run=ramp=>{const sim=new Simulation(levels,parts,'bathtub',{ramp});sim.launch();for(let i=0;i<60*120&&sim.state!=='complete';i++)sim.step({boost:true},1/60);return sim.result.distance};assert.ok(run(4)>run(0)*1.2)});
