package com.jeltedeproft.flylikeaneagle;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.InputAdapter;
import com.badlogic.gdx.InputMultiplexer;
import com.badlogic.gdx.Preferences;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.Matrix4;
import com.badlogic.gdx.math.MathUtils;
import com.badlogic.gdx.math.Vector2;
import com.badlogic.gdx.physics.box2d.*;
import com.badlogic.gdx.utils.IntSet;
import com.badlogic.gdx.utils.viewport.ExtendViewport;

public class FlyLikeAnEagle extends ApplicationAdapter {
    public interface Ui {void update(String state);}
    private static final float STEP=1f/60f, LAUNCH_X=52.5f, LANDING_RESULT_DELAY=.45f;
    private static final int MAX=4, MAX_GENERATION=2, TRAIL_POINTS=18;
    private static final Vector2[] RAMP={new Vector2(-20,15),new Vector2(-10,14),new Vector2(0,11),new Vector2(12,6),new Vector2(24,2.2f),new Vector2(32,1.4f),new Vector2(38,1.7f),new Vector2(43,2.5f),new Vector2(47,3.8f),new Vector2(50,5.2f),new Vector2(LAUNCH_X,6.8f)};
    private static final Vector2[] LAND={new Vector2(62,6.8f),new Vector2(70,5.2f),new Vector2(82,3),new Vector2(96,1.1f),new Vector2(112,0),new Vector2(1200,0)};
    private static final float[] PX={72,88,108,132,160}, PY={10,12,9,7,5};
    private static final float SKY_CELL=16f;
    private enum RunState{RUNNING,RESULT,SHOP,FINISHED} private enum Outcome{NONE,CLEAN,CRASH}
    private World world; private Body sled; private OrthographicCamera camera; private ExtendViewport viewport; private ShapeRenderer shapes; private Preferences progress;
    private SpriteBatch hudBatch,artBatch; private BitmapFont hudFont; private final Matrix4 hudProjection=new Matrix4();
    private Texture skyTexture,cloudTexture,landscapeTexture,iconTexture,propsTexture,fireTexture;
    private AirshipAnimationManager airshipAnimation;
    private GameHud gameHud;
    private float accumulator,stationaryTime,landingTimer,bestDistance,touchdownDistance,finalDistance,trailTimer;
    private boolean launched,touchedLanding,touchLeft,touchRight; private int groundContacts,trailCount; private RunState state; private Outcome outcome;
    private int points,speedLevel,glideLevel,controlLevel,rampLevel,aeroLevel,bounceLevel,slideLevel,lastReward,pickupPoints;
    private boolean wingsPart,suspensionPart,tailPart,boosterPart; private int vehicleType;
    private final Ui ui;
    private final boolean[] pickupCollected=new boolean[PX.length]; private final IntSet collectedSky=new IntSet(); private final float[] trailX=new float[TRAIL_POINTS],trailY=new float[TRAIL_POINTS];

    public FlyLikeAnEagle(){this(null);} public FlyLikeAnEagle(Ui ui){this.ui=ui;}

    @Override public void create(){world=new World(new Vector2(0,-7.4f),true);camera=new OrthographicCamera();viewport=new ExtendViewport(44,24.75f,camera);shapes=new ShapeRenderer();artBatch=new SpriteBatch();airshipAnimation=new AirshipAnimationManager("fly.atlas");skyTexture=texture("Pixel Airship/Pixel Airship/10_Backgrounds/BG.png");cloudTexture=texture("Pixel Airship/Pixel Airship/10_Backgrounds/Cloud.png");landscapeTexture=texture("aviation-landscape-v2.png");iconTexture=texture("Pixel Airship/Pixel Airship/09_UI/Icons/UI_Icons_Red.png");propsTexture=texture("Pixel Airship/Pixel Airship/05_Props/Ship_Props.png");fireTexture=texture("Pixel Airship/Pixel Airship/04_Effects/Fire/Fire.png");if(Gdx.app.getType()==com.badlogic.gdx.Application.ApplicationType.Desktop){hudBatch=new SpriteBatch();hudFont=new BitmapFont(Gdx.files.internal("ui-font.fnt"));hudFont.getRegion().getTexture().setFilter(com.badlogic.gdx.graphics.Texture.TextureFilter.Nearest,com.badlogic.gdx.graphics.Texture.TextureFilter.Nearest);hudFont.getData().setScale(1.35f);}progress=Gdx.app.getPreferences("fly-like-an-eagle-progress");load();terrain();contacts();startRun();Gdx.input.setInputProcessor(new InputAdapter(){@Override public boolean touchDown(int x,int y,int pointer,int button){if(state!=RunState.RUNNING)menuTap(x,y);return false;}});resize(Gdx.graphics.getWidth(),Gdx.graphics.getHeight());}
    private Texture texture(String path){Texture t=new Texture(Gdx.files.internal(path));t.setFilter(Texture.TextureFilter.Nearest,Texture.TextureFilter.Nearest);return t;}
    private void load(){points=progress.getInteger("points",progress.getInteger("coins",0));speedLevel=Math.min(MAX,progress.getInteger("speed",0));glideLevel=Math.min(MAX,progress.getInteger("glide",0));controlLevel=Math.min(MAX,progress.getInteger("control",0));rampLevel=Math.min(MAX,progress.getInteger("ramp",0));aeroLevel=Math.min(MAX,progress.getInteger("aero",0));bounceLevel=Math.min(MAX,progress.getInteger("bounce",0));slideLevel=Math.min(MAX,progress.getInteger("slide",0));bestDistance=progress.getFloat("bestLanding",progress.getFloat("best",0));vehicleType=MathUtils.clamp(progress.getInteger("generation",0),0,MAX_GENERATION);wingsPart=progress.getBoolean("genWings",false);suspensionPart=progress.getBoolean("genGear",false);tailPart=progress.getBoolean("genTail",false);boosterPart=progress.getBoolean("genEngine",false);}
    private void save(){progress.putInteger("points",points).putInteger("speed",speedLevel).putInteger("glide",glideLevel).putInteger("control",controlLevel).putInteger("ramp",rampLevel).putInteger("aero",aeroLevel).putInteger("bounce",bounceLevel).putInteger("slide",slideLevel).putInteger("generation",vehicleType).putBoolean("genWings",wingsPart).putBoolean("genGear",suspensionPart).putBoolean("genTail",tailPart).putBoolean("genEngine",boosterPart).putFloat("bestLanding",bestDistance).flush();}
    private void terrain(){chain(RAMP,"ramp");chain(LAND,"landing");}
    private void chain(Vector2[] v,String tag){Body b=world.createBody(new BodyDef());ChainShape s=new ChainShape();s.createChain(v);Fixture f=b.createFixture(s,0);f.setFriction("landing".equals(tag)?.8f:.25f);f.setUserData(tag);s.dispose();}
    private boolean pair(Fixture a,Fixture b,String x,String y){Object au=a.getUserData(),bu=b.getUserData();return(x.equals(au)&&y.equals(bu))||(x.equals(bu)&&y.equals(au));}
    private void contacts(){world.setContactListener(new ContactListener(){public void beginContact(Contact c){Fixture a=c.getFixtureA(),b=c.getFixtureB();if(pair(a,b,"sled","landing")&&launched){groundContacts++;stationaryTime=0;if(!touchedLanding){touchedLanding=true;touchdownDistance=Math.max(0,sled.getPosition().x-LAUNCH_X);outcome=landing();}}}public void endContact(Contact c){if(pair(c.getFixtureA(),c.getFixtureB(),"sled","landing")&&launched){groundContacts=Math.max(0,groundContacts-1);stationaryTime=0;}}public void preSolve(Contact c,Manifold m){}public void postSolve(Contact c,ContactImpulse i){}});}
    private Outcome landing(){float deg=norm(sled.getAngle()*MathUtils.radiansToDegrees),err=Math.abs(norm(deg+17));return err<=38&&Math.abs(sled.getAngularVelocity())<=4.5f&&-sled.getLinearVelocity().y<=20?Outcome.CLEAN:Outcome.CRASH;}
    private float norm(float v){while(v>180)v-=360;while(v<-180)v+=360;return v;}

    private void startRun(){if(sled!=null)world.destroyBody(sled);BodyDef d=new BodyDef();d.type=BodyDef.BodyType.DynamicBody;d.position.set(-14,16.2f);d.angle=-.08f;d.angularDamping=.7f+aeroLevel*.04f+(tailPart?.28f:0f);sled=world.createBody(d);PolygonShape s=new PolygonShape();s.setAsBox(1.4f,.28f);FixtureDef fd=new FixtureDef();fd.shape=s;fd.density=1.2f;fd.friction=.3f+slideLevel*.12f+(suspensionPart?.08f:0f);fd.restitution=.03f+bounceLevel*.05f+(suspensionPart?.04f:0f);Fixture f=sled.createFixture(fd);f.setUserData("sled");s.dispose();sled.setLinearVelocity(9+speedLevel*1.2f+(boosterPart?1.8f:0f),0);accumulator=stationaryTime=landingTimer=touchdownDistance=finalDistance=trailTimer=0;trailCount=groundContacts=lastReward=pickupPoints=0;launched=touchedLanding=touchLeft=touchRight=false;outcome=Outcome.NONE;state=RunState.RUNNING;for(int i=0;i<pickupCollected.length;i++)pickupCollected[i]=false;camera.position.set(-9,10,0);camera.update();}
    @Override public void render(){float dt=Math.min(Gdx.graphics.getDeltaTime(),.25f);if(gameHud==null)createGameHud();airshipAnimation.update(dt);if(state==RunState.RUNNING){controls();rampAssist();airAssist();step(dt);trail(dt);pickups();runState(dt);}else if(Gdx.input.isKeyJustPressed(Input.Keys.R)||Gdx.input.isKeyJustPressed(Input.Keys.SPACE))startRun();camera();draw();drawBackdrop();drawTerrainOverlay();drawWorldSprites();drawAirship();drawMenuPanels();drawGarage();drawGarageAirship();title();gameHud.update(gameStateData());gameHud.render(dt);}
    private void createGameHud(){gameHud=new GameHud(new GameHud.Actions(){public void openShop(){state=RunState.SHOP;}public void launch(){startRun();}public void buyUpgrade(int index){buy(index);}public void buyPart(int index){FlyLikeAnEagle.this.buyPart(index);}public void advance(){advanceGeneration();}});Gdx.input.setInputProcessor(new InputMultiplexer(gameHud.input(),Gdx.input.getInputProcessor()));}
    private String gameStateData(){String st=state==RunState.RESULT?"RESULT":state==RunState.SHOP?"SHOP":launched?(groundContacts>0?"GROUND":"AIR"):"RAMP";int land=state==RunState.RUNNING?(touchedLanding?Math.round(touchdownDistance):-1):Math.round(finalDistance);return"FLYEAGLE|DIST="+Math.round(distance())+"|LAND="+land+"|BEST="+Math.round(bestDistance)+"|POINTS="+points+"|REWARD="+lastReward+"|SPEED="+token(speedLevel)+"|GLIDE="+token(glideLevel)+"|CONTROL="+token(controlLevel)+"|RAMP="+token(rampLevel)+"|AERO="+token(aeroLevel)+"|BOUNCE="+token(bounceLevel)+"|SLIDE="+token(slideLevel)+"|WINGS="+partToken(wingsPart,partCost(0))+"|SUSP="+partToken(suspensionPart,partCost(1))+"|TAIL="+partToken(tailPart,partCost(2))+"|BOOSTER="+partToken(boosterPart,partCost(3))+"|GEN="+(vehicleType+1)+"|MODEL="+generationName()+"|DEV="+totalLevels()+"/"+(MAX*7)+"|CANADVANCE="+(fullyDeveloped()&&vehicleType<MAX_GENERATION)+"|STATE="+st;}

    private void menuTap(int screenX,int screenY){float x=MathUtils.clamp(screenX/(float)Gdx.graphics.getWidth(),0,.999f),y=MathUtils.clamp(screenY/(float)Gdx.graphics.getHeight(),0,.999f);if(state==RunState.RESULT){if(y>.5f&&y<.82f)state=RunState.SHOP;return;}if(state!=RunState.SHOP)return;if(y>.9f){startRun();return;}if(x<.48f)return;int col=Math.min(3,(int)(((x-.48f)/.52f)*4));if(y>.12f&&y<.3f){buy(col);return;}if(y<.49f){int type=4+col;if(type<7)buy(type);return;}if(y<.68f){buyPart(col);return;}if(y<.88f&&col==0)advanceGeneration();}
    private int level(int t){switch(t){case 0:return speedLevel;case 1:return glideLevel;case 2:return controlLevel;case 3:return rampLevel;case 4:return aeroLevel;case 5:return bounceLevel;default:return slideLevel;}}
    private void buy(int t){int l=level(t);if(l>=MAX)return;int c=cost(l);if(points<c)return;points-=c;switch(t){case 0:speedLevel++;break;case 1:glideLevel++;break;case 2:controlLevel++;break;case 3:rampLevel++;break;case 4:aeroLevel++;break;case 5:bounceLevel++;break;case 6:slideLevel++;break;}save();}
    private int cost(int l){return 20+l*l*10+vehicleType*15;}
    private int totalLevels(){return speedLevel+glideLevel+controlLevel+rampLevel+aeroLevel+bounceLevel+slideLevel;}
    private int ownedParts(){return(wingsPart?1:0)+(suspensionPart?1:0)+(tailPart?1:0)+(boosterPart?1:0);}
    private int development(){return totalLevels()+ownedParts();}
    private boolean fullyDeveloped(){return totalLevels()==MAX*7&&ownedParts()==4;}
    private void advanceGeneration(){if(!fullyDeveloped()||vehicleType>=MAX_GENERATION)return;vehicleType++;airshipAnimation.reset();speedLevel=glideLevel=controlLevel=rampLevel=aeroLevel=bounceLevel=slideLevel=0;wingsPart=suspensionPart=tailPart=boosterPart=false;save();}
    private int partCost(int t){return(t==0?120:t==1?100:t==2?110:150)+vehicleType*30;}
    private boolean hasPart(int t){return t==0?wingsPart:t==1?suspensionPart:t==2?tailPart:boosterPart;}
    private void buyPart(int t){if(hasPart(t))return;int c=partCost(t);if(points<c)return;points-=c;if(t==0)wingsPart=true;else if(t==1)suspensionPart=true;else if(t==2)tailPart=true;else boosterPart=true;save();}
    private String generationName(){return vehicleType==0?"WOODEN GLIDER":vehicleType==1?"PROPELLER PLANE":"JET";}
    private Color bodyColor(){return vehicleType==0?new Color(.48f,.25f,.08f,1):vehicleType==1?new Color(.9f,.22f,.12f,1):new Color(.35f,.85f,.95f,1);}
    private String vehicleToken(int t){if(t<vehicleType)return"DEVELOPED";if(t==vehicleType)return generationName();if(t==vehicleType+1)return fullyDeveloped()?"ADVANCE":"LOCKED";return"LOCKED";}
    private String partToken(boolean owned,int cost){return owned?"OWNED":"BUY "+cost;}
    private void controls(){if(!launched&&sled.getPosition().x>52.1f)launched=true;touchLeft=touchRight=false;boolean left=Gdx.input.isKeyPressed(Input.Keys.LEFT)||Gdx.input.isKeyPressed(Input.Keys.A),right=Gdx.input.isKeyPressed(Input.Keys.RIGHT)||Gdx.input.isKeyPressed(Input.Keys.D);if(Gdx.input.isTouched()){touchLeft=Gdx.input.getX()<Gdx.graphics.getWidth()/2;touchRight=!touchLeft;left|=touchLeft;right|=touchRight;}if(!launched||groundContacts>0)return;float maxSpin=1.7f+controlLevel*.22f-(tailPart?.18f:0f);float targetSpin=left&&!right?maxSpin:right&&!left?-maxSpin:0f;float current=sled.getAngularVelocity();float response=3.4f+controlLevel*.45f+(tailPart?.55f:0f);float next=current+(targetSpin-current)*Math.min(1f,response*STEP);sled.setAngularVelocity(MathUtils.clamp(next,-maxSpin,maxSpin));}
    private void rampAssist(){if(launched)return;float x=sled.getPosition().x;if(x>30&&x<52.4f){Vector2 v=sled.getLinearVelocity();float target=16+speedLevel*1.4f+rampLevel*1.8f+(boosterPart?2.4f:0f)+(vehicleType==1?3f:vehicleType==2?1f:0f);if(v.x<target)sled.setLinearVelocity(target,v.y);}}
    private void airAssist(){if(!launched||groundContacts>0)return;Vector2 v=sled.getLinearVelocity();float lift=vehicleType==2?1.2f:0;if(glideLevel>0&&v.y<0)lift+=glideLevel*.32f;if(aeroLevel>0)lift+=Math.min(1.8f,Math.max(0,v.x)*aeroLevel*.012f);if(wingsPart)lift+=Math.min(1.15f,Math.max(0,v.x)*.04f);lift=Math.min(5.2f,lift);float thrust=aeroLevel*.22f+(wingsPart?.22f:0f)+(vehicleType==1?1.3f:0f);sled.applyForceToCenter(thrust,lift-v.y*.08f,true);if(boosterPart&&v.x<25f)sled.applyForceToCenter(2.2f,0,true);}
    private void step(float dt){accumulator+=dt;while(accumulator>=STEP){world.step(STEP,8,3);accumulator-=STEP;}}
    private void trail(float dt){if(!launched||groundContacts>0)return;trailTimer+=dt;if(trailTimer<.08f)return;trailTimer=0;for(int i=Math.min(trailCount,TRAIL_POINTS-1);i>0;i--){trailX[i]=trailX[i-1];trailY[i]=trailY[i-1];}trailX[0]=sled.getPosition().x;trailY[0]=sled.getPosition().y;if(trailCount<TRAIL_POINTS)trailCount++;}
    private int skyHash(int cell,int slot){int h=cell*0x45d9f3b+slot*0x119de1f3+0x6d2b79f5;h=(h^(h>>>16))*0x45d9f3b;return(h^(h>>>16))&0x7fffffff;}
    private float skyX(int cell,int slot){return cell*SKY_CELL+2f+(skyHash(cell,slot)%1100)/100f;}
    private float skyY(int cell,int slot){float x=skyX(cell,slot),rise=Math.min(30f,Math.max(0,x-55f)*.045f);return 6f+rise+(skyHash(cell,slot+17)%1500)/100f;}
    private int skyType(int cell,int slot){int type=skyHash(cell,slot+31)%7;float y=skyY(cell,slot);return y>29&&type>=4?6:type;}
    private int skyId(int cell,int slot){return cell*3+slot;}
    private void pickups(){if(!launched){collectedSky.clear();return;}if(groundContacts>0)return;Vector2 p=sled.getPosition();for(int i=0;i<PX.length;i++){if(pickupCollected[i])continue;float dx=p.x-PX[i],dy=p.y-PY[i];if(dx*dx+dy*dy<3.2f){pickupCollected[i]=true;pickupPoints+=5;}}int first=(int)Math.floor((p.x-18)/SKY_CELL),last=(int)Math.ceil((p.x+18)/SKY_CELL);for(int cell=first;cell<=last;cell++)for(int slot=0;slot<2;slot++){float x=skyX(cell,slot),y=skyY(cell,slot),dx=p.x-x,dy=p.y-y;int type=skyType(cell,slot),id=skyId(cell,slot);if((type==0||type==1)&&!collectedSky.contains(id)&&dx*dx+dy*dy<3.6f){collectedSky.add(id);pickupPoints+=15;Vector2 v=sled.getLinearVelocity();sled.setLinearVelocity(v.x+2.4f,v.y+1.1f);}else if(type==2&&dx*dx+dy*dy<10f)sled.applyForceToCenter(-1.2f,-5.5f,true);}}
    private void runState(float dt){if(!touchedLanding)return;landingTimer+=dt;if(groundContacts>0){Vector2 v=sled.getLinearVelocity();float braking=Math.max(.25f,1f-dt*(5f+slideLevel));sled.setLinearVelocity(v.x*braking,v.y);sled.setAngularVelocity(sled.getAngularVelocity()*Math.max(.2f,1f-dt*8f));}if(landingTimer>=LANDING_RESULT_DELAY)finish();}
    private void finish(){finalDistance=Math.max(0,sled.getPosition().x-LAUNCH_X);bestDistance=Math.max(bestDistance,finalDistance);lastReward=Math.round(finalDistance)+pickupPoints+(outcome==Outcome.CLEAN?20:0);points+=lastReward;save();state=RunState.RESULT;}
    private float distance(){return launched?Math.max(0,sled.getPosition().x-LAUNCH_X):0;}
    private void camera(){Vector2 p=sled.getPosition();camera.position.x+=(p.x+5-camera.position.x)*.1f;float landingFloor=Math.min(10f,camera.viewportHeight*.5f-1f),targetY=launched?Math.max(landingFloor,p.y+1.5f):Math.max(8,p.y+1);camera.position.y+=(targetY-camera.position.y)*(targetY>camera.position.y?.16f:.07f);float top=camera.position.y+camera.viewportHeight*.4f;if(p.y>top)camera.position.y=p.y-camera.viewportHeight*.32f;camera.update();}

    private void drawBackdrop(){float w=camera.viewportWidth,h=camera.viewportHeight;artBatch.setProjectionMatrix(camera.combined);artBatch.begin();artBatch.draw(landscapeTexture,camera.position.x-w*.5f,camera.position.y-h*.5f,w,h);artBatch.end();}
    private void drawTerrainOverlay(){shapes.setProjectionMatrix(camera.combined);shapes.begin(ShapeRenderer.ShapeType.Filled);shapes.setColor(.12f,.12f,.2f,1);fill(RAMP);fill(LAND);shapes.end();shapes.begin(ShapeRenderer.ShapeType.Line);shapes.setColor(.72f,.68f,.24f,1);line(RAMP);line(LAND);shapes.setColor(.35f,.52f,.25f,1);for(int i=0;i<RAMP.length-1;i++)shapes.line(RAMP[i].x,RAMP[i].y-.18f,RAMP[i+1].x,RAMP[i+1].y-.18f);for(int i=0;i<LAND.length-1;i++)shapes.line(LAND[i].x,LAND[i].y-.18f,LAND[i+1].x,LAND[i+1].y-.18f);shapes.end();}
    private void drawWorldSprites(){if(state!=RunState.RUNNING)return;TextureRegion plus=new TextureRegion(iconTexture,48,0,16,16),heart=new TextureRegion(iconTexture,32,0,16,16),gear=new TextureRegion(iconTexture,112,0,16,16),fire=new TextureRegion(fireTexture,0,0,16,16);artBatch.setProjectionMatrix(camera.combined);artBatch.begin();for(int i=0;i<PX.length;i++)if(!pickupCollected[i])artBatch.draw(plus,PX[i]-.7f,PY[i]-.7f,1.4f,1.4f);float halfW=camera.viewportWidth*.62f;int first=(int)Math.floor((camera.position.x-halfW)/SKY_CELL),last=(int)Math.ceil((camera.position.x+halfW)/SKY_CELL);for(int cell=first;cell<=last;cell++)for(int slot=0;slot<2;slot++){float x=skyX(cell,slot),y=skyY(cell,slot);int type=skyType(cell,slot),id=skyId(cell,slot);if((type==0||type==1)&&!collectedSky.contains(id))artBatch.draw(type==0?heart:gear,x-.8f,y-.8f,1.6f,1.6f);else if(type==2)artBatch.draw(fire,x-1f,y-1f,2f,2f);}artBatch.end();}
    private TextureRegion airshipFrame(){return airshipAnimation.getFrame();}
    private void drawAirship(){Vector2 p=sled.getPosition();float a=sled.getAngle()*MathUtils.radiansToDegrees,w=vehicleType==2?7.8f:7.2f,h=4.8f;artBatch.setProjectionMatrix(camera.combined);artBatch.begin();TextureRegion ship=airshipFrame();artBatch.draw(ship,p.x-w*.5f,p.y-h*.48f,w*.5f,h*.48f,w,h,1,1,a);artBatch.end();}
    private void drawGarageAirship(){if(state!=RunState.SHOP)return;float w=Gdx.graphics.getWidth(),h=Gdx.graphics.getHeight(),sw=Math.min(w*.38f,h*.58f),sh=sw*(vehicleType==2?400f/652f:390f/585f),x=w*.235f-sw*.5f,y=h*.51f-sh*.5f;artBatch.setProjectionMatrix(hudProjection);artBatch.begin();artBatch.draw(skyTexture,0,0,w*.47f,h);artBatch.draw(airshipFrame(),x,y,sw,sh);artBatch.end();}

    private void draw(){Gdx.gl.glClearColor(.42f,.72f,.95f,1);Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);shapes.setProjectionMatrix(camera.combined);shapes.begin(ShapeRenderer.ShapeType.Filled);shapes.setColor(1,.9f,.35f,1);shapes.circle(22,22,2.2f,28);cloud(-2,18,1.2f);cloud(36,20,.9f);cloud(88,17,1.1f);cloud(140,19,1);cloud(205,16,1.15f);shapes.setColor(.23f,.55f,.25f,1);fill(RAMP);fill(LAND);shapes.setColor(.95f,.78f,.18f,1);shapes.rect(LAUNCH_X-.35f,6.6f,.7f,.4f);for(float x=72;x<=1120;x+=40)post(x,x<112?1:.3f);for(int i=0;i<PX.length;i++)if(!pickupCollected[i]){shapes.setColor(1,.78f,.12f,1);shapes.circle(PX[i],PY[i],.48f,18);shapes.setColor(1,.94f,.45f,1);shapes.circle(PX[i],PY[i],.22f,14);}if(launched)for(int i=trailCount-1;i>=0;i--){float z=.08f+(trailCount-i)*.012f;shapes.setColor(1,1,1,.18f+(trailCount-i)*.018f);shapes.circle(trailX[i],trailY[i],z,10);}Vector2 p=sled.getPosition();float a=sled.getAngle()*MathUtils.radiansToDegrees;if(wingsPart){shapes.setColor(.85f,.88f,.95f,1);shapes.rect(p.x-.15f,p.y-.15f,.15f,.15f,2.4f,.3f,1,1,a);}if(tailPart){shapes.setColor(.25f,.35f,.55f,1);shapes.rect(p.x-1.55f,p.y-.05f,0,0,.55f,.75f,1,1,a);}if(boosterPart){shapes.setColor(.25f,.25f,.3f,1);shapes.rect(p.x-1.8f,p.y-.17f,0,0,.55f,.34f,1,1,a);if(launched&&groundContacts==0){shapes.setColor(1f,.55f,.1f,.9f);shapes.circle(p.x-1.95f,p.y-.02f,.25f,12);}}shapes.setColor(bodyColor());shapes.rect(p.x-1.4f,p.y-.28f,1.4f,.28f,2.8f,.56f,1,1,a);shapes.setColor(Color.DARK_GRAY);float wheel=.22f+(suspensionPart?.09f:0f);shapes.circle(p.x-.8f,p.y-.42f,wheel,12);shapes.circle(p.x+.8f,p.y-.42f,wheel,12);if(state==RunState.RUNNING&&(touchLeft||touchRight)){shapes.setColor(1,1,1,.6f);shapes.circle(p.x+(touchLeft?-2.4f:2.4f),p.y+1.8f,.55f,18);}if(state==RunState.FINISHED){shapes.setColor(outcome==Outcome.CLEAN?new Color(.35f,.95f,.45f,.9f):new Color(.95f,.25f,.2f,.9f));shapes.circle(p.x,p.y+3,1.25f,24);}shapes.end();shapes.begin(ShapeRenderer.ShapeType.Line);shapes.setColor(Color.WHITE);line(RAMP);line(LAND);shapes.end();}
    private void cloud(float x,float y,float s){shapes.setColor(1,1,1,.72f);shapes.circle(x,y,1.15f*s,18);shapes.circle(x+1.1f*s,y+.18f*s,.9f*s,18);shapes.circle(x-1*s,y+.12f*s,.78f*s,18);}
    private void drawSkyObjects(){if(state!=RunState.RUNNING)return;float halfW=camera.viewportWidth*.62f,halfH=camera.viewportHeight*.62f;int first=(int)Math.floor((camera.position.x-halfW)/SKY_CELL),last=(int)Math.ceil((camera.position.x+halfW)/SKY_CELL);shapes.setProjectionMatrix(camera.combined);shapes.begin(ShapeRenderer.ShapeType.Filled);for(int cell=first;cell<=last;cell++)for(int slot=0;slot<2;slot++){float x=skyX(cell,slot),y=skyY(cell,slot);if(y<camera.position.y-halfH||y>camera.position.y+halfH)continue;int type=skyType(cell,slot),id=skyId(cell,slot);if((type==0||type==1)&&!collectedSky.contains(id)){shapes.setColor(type==0?.72f:.2f,.25f,type==0?1f:.95f,1);shapes.circle(x,y,1.05f,24);shapes.setColor(.42f,.72f,.95f,1);shapes.circle(x,y,.62f,24);}else if(type==2){shapes.setColor(.25f,.28f,.38f,.95f);shapes.circle(x-1,y,.65f,16);shapes.circle(x,y+.25f,.9f,18);shapes.circle(x+1,y,.72f,16);shapes.setColor(1f,.9f,.2f,1);shapes.triangle(x-.2f,y-.55f,x+.28f,y-.55f,x-.05f,y-1.25f);shapes.triangle(x-.05f,y-1.25f,x+.55f,y-.95f,x+.28f,y-.55f);}else if(type==3){shapes.setColor(.95f,.25f,.2f,.95f);shapes.circle(x,y,.75f,20);shapes.setColor(.35f,.2f,.1f,1);shapes.rect(x-.25f,y-1.3f,.5f,.36f);shapes.setColor(Color.WHITE);shapes.rect(x-.03f,y-.92f,.06f,.48f);}else if(type==4){shapes.setColor(.15f,.18f,.25f,1);shapes.triangle(x-1,y,x,y+.35f,x-.15f,y);shapes.triangle(x+.15f,y,x,y+.35f,x+1,y);}else if(type==5){shapes.setColor(1f,.45f,.15f,1);shapes.triangle(x,y+.8f,x-.65f,y,x+.65f,y);shapes.triangle(x,y-.8f,x-.65f,y,x+.65f,y);shapes.setColor(Color.WHITE);shapes.rect(x-.025f,y-1.7f,.05f,.9f);}else if(type==6){shapes.setColor(.82f,.87f,.92f,1);shapes.rect(x-.8f,y-.22f,1.6f,.44f);shapes.setColor(.18f,.35f,.65f,1);shapes.rect(x-1.65f,y-.08f,.85f,.16f);shapes.rect(x+.8f,y-.08f,.85f,.16f);shapes.setColor(1f,.25f,.1f,1);shapes.circle(x,y,.2f,12);}}shapes.end();}
    private Vector2 local(Vector2 p,float a,float x,float y){float c=MathUtils.cosDeg(a),s=MathUtils.sinDeg(a);return new Vector2(p.x+x*c-y*s,p.y+x*s+y*c);}
    private void partRect(Vector2 p,float a,float x,float y,float w,float h,Color color){Vector2 q=local(p,a,x,y);shapes.setColor(color);shapes.rect(q.x,q.y,0,0,w,h,1,1,a);}
    private void partCircle(Vector2 p,float a,float x,float y,float radius,Color color){Vector2 q=local(p,a,x,y);shapes.setColor(color);shapes.circle(q.x,q.y,radius,14);}
    private void drawParts(){if(state==RunState.SHOP||!wingsPart&&!suspensionPart&&!tailPart&&!boosterPart)return;Vector2 p=sled.getPosition();float a=sled.getAngle()*MathUtils.radiansToDegrees;shapes.setProjectionMatrix(camera.combined);shapes.begin(ShapeRenderer.ShapeType.Filled);if(wingsPart){partRect(p,a,-.85f,-.72f,2.35f,1.45f,new Color(.82f,.9f,1,1));partRect(p,a,-.55f,-.48f,1.75f,.95f,new Color(.55f,.72f,.92f,1));}if(tailPart){partRect(p,a,-1.32f,.18f,.62f,1.05f,new Color(.2f,.35f,.58f,1));partRect(p,a,-1.55f,.08f,.8f,.28f,new Color(.35f,.55f,.78f,1));}if(boosterPart){partRect(p,a,-1.9f,-.2f,.7f,.4f,Color.DARK_GRAY);if(launched&&groundContacts==0){partCircle(p,a,-2.12f,0,.3f,new Color(1f,.35f,.05f,.9f));partCircle(p,a,-2.02f,0,.18f,new Color(1f,.9f,.15f,1));}}partRect(p,a,-1.4f,-.28f,2.8f,.56f,new Color(.9f,.22f,.12f,1));if(suspensionPart){partRect(p,a,-.9f,-.56f,.14f,.38f,new Color(.8f,.85f,.9f,1));partRect(p,a,.76f,-.56f,.14f,.38f,new Color(.8f,.85f,.9f,1));partCircle(p,a,-.8f,-.68f,.34f,Color.DARK_GRAY);partCircle(p,a,.8f,-.68f,.34f,Color.DARK_GRAY);}shapes.end();}
    private void partTri(Vector2 p,float a,float x1,float y1,float x2,float y2,float x3,float y3,Color color){Vector2 q1=local(p,a,x1,y1),q2=local(p,a,x2,y2),q3=local(p,a,x3,y3);shapes.setColor(color);shapes.triangle(q1.x,q1.y,q2.x,q2.y,q3.x,q3.y);}
    private void drawVehicleSkin(){if(state==RunState.SHOP||vehicleType==0)return;Vector2 p=sled.getPosition();float a=sled.getAngle()*MathUtils.radiansToDegrees;shapes.setProjectionMatrix(camera.combined);shapes.begin(ShapeRenderer.ShapeType.Filled);if(vehicleType==1){partRect(p,a,-1.35f,-.38f,2.5f,.76f,new Color(.95f,.36f,.08f,1));partTri(p,a,1.15f,-.38f,1.85f,0,1.15f,.38f,new Color(1f,.75f,.18f,1));partTri(p,a,-.65f,-.35f,-1.25f,-.85f,.2f,-.35f,new Color(.3f,.45f,.72f,1));if(launched&&groundContacts==0)partTri(p,a,-1.35f,-.28f,-2.15f,0,-1.35f,.28f,new Color(1f,.75f,.1f,1));}else{partRect(p,a,-1.45f,-.25f,2.9f,.5f,new Color(.35f,.85f,.95f,1));partCircle(p,a,0,.15f,.68f,new Color(.65f,.95f,1f,1));partCircle(p,a,-.85f,-.28f,.18f,new Color(1f,.85f,.25f,1));partCircle(p,a,0,-.32f,.18f,new Color(1f,.85f,.25f,1));partCircle(p,a,.85f,-.28f,.18f,new Color(1f,.85f,.25f,1));}shapes.end();}
    private void drawGarage(){if(state!=RunState.SHOP)return;float w=Gdx.graphics.getWidth(),h=Gdx.graphics.getHeight(),cx=w*.24f,cy=h*.53f,s=Math.min(w*.065f,h*.12f);shapes.setProjectionMatrix(hudProjection);shapes.begin(ShapeRenderer.ShapeType.Filled);shapes.setColor(.04f,.08f,.14f,.86f);shapes.rect(0,0,w*.47f,h);shapes.setColor(.15f,.22f,.3f,1);shapes.rect(w*.04f,h*.22f,w*.4f,h*.48f);if(wingsPart){shapes.setColor(.42f,.7f,1,1);shapes.triangle(cx-s*.7f,cy-s*.1f,cx+s*1.45f,cy-s*1.25f,cx+s*.85f,cy+s*.15f);shapes.setColor(.72f,.88f,1,1);shapes.triangle(cx-s*.5f,cy+s*.05f,cx+s*1.2f,cy+s*1.1f,cx+s*.55f,cy-s*.05f);}if(tailPart){shapes.setColor(.25f,.5f,.85f,1);shapes.triangle(cx-s*1.55f,cy+s*.15f,cx-s*1.2f,cy+s*1.25f,cx-s*.75f,cy+s*.15f);}if(boosterPart){shapes.setColor(Color.DARK_GRAY);shapes.rect(cx-s*1.8f,cy-s*.22f,s*.65f,s*.44f);shapes.setColor(1f,.45f,.08f,1);shapes.triangle(cx-s*1.8f,cy-s*.2f,cx-s*2.35f,cy,cx-s*1.8f,cy+s*.2f);}shapes.setColor(.92f,.2f,.12f,1);shapes.rect(cx-s*1.35f,cy-s*.3f,s*2.7f,s*.6f);shapes.setColor(.12f,.18f,.24f,1);float wy=cy-s*(suspensionPart?.82f:.5f),wr=s*(suspensionPart?.38f:.25f);if(suspensionPart){shapes.setColor(.75f,.85f,.95f,1);shapes.rect(cx-s*.9f,cy-s*.72f,s*.16f,s*.5f);shapes.rect(cx+s*.72f,cy-s*.72f,s*.16f,s*.5f);shapes.setColor(.12f,.18f,.24f,1);}shapes.circle(cx-s*.78f,wy,wr,18);shapes.circle(cx+s*.78f,wy,wr,18);shapes.end();}
    private void drawGarageVehicleSkin(){if(state!=RunState.SHOP||vehicleType==0)return;float w=Gdx.graphics.getWidth(),h=Gdx.graphics.getHeight(),cx=w*.24f,cy=h*.53f,s=Math.min(w*.065f,h*.12f);shapes.setProjectionMatrix(hudProjection);shapes.begin(ShapeRenderer.ShapeType.Filled);if(vehicleType==1){shapes.setColor(.95f,.36f,.08f,1);shapes.rect(cx-s*1.35f,cy-s*.38f,s*2.5f,s*.76f);shapes.setColor(1f,.75f,.18f,1);shapes.triangle(cx+s*1.15f,cy-s*.38f,cx+s*1.85f,cy,cx+s*1.15f,cy+s*.38f);shapes.setColor(.3f,.45f,.72f,1);shapes.triangle(cx-s*.65f,cy-s*.35f,cx-s*1.25f,cy-s*.85f,cx+s*.2f,cy-s*.35f);}else{shapes.setColor(.35f,.85f,.95f,1);shapes.rect(cx-s*1.45f,cy-s*.25f,s*2.9f,s*.5f);shapes.setColor(.65f,.95f,1f,1);shapes.circle(cx,cy+s*.15f,s*.68f,24);shapes.setColor(1f,.85f,.25f,1);shapes.circle(cx-s*.85f,cy-s*.28f,s*.18f,14);shapes.circle(cx,cy-s*.32f,s*.18f,14);shapes.circle(cx+s*.85f,cy-s*.28f,s*.18f,14);}shapes.end();}
    private void drawMenuPanels(){if(state==RunState.RUNNING)return;float w=Gdx.graphics.getWidth(),h=Gdx.graphics.getHeight();shapes.setProjectionMatrix(hudProjection);shapes.begin(ShapeRenderer.ShapeType.Filled);if(state==RunState.RESULT){shapes.setColor(.06f,.12f,.2f,1);shapes.rect(w*.25f,h*.18f,w*.5f,h*.64f);shapes.setColor(1f,.65f,.12f,1);shapes.rect(w*.32f,h*.22f,w*.36f,h*.13f);}else if(state==RunState.SHOP){shapes.setColor(.025f,.055f,.1f,1);shapes.rect(w*.47f,0,w*.53f,h);for(int row=0;row<4;row++)for(int col=0;col<4;col++){if(row==1&&col==3||row==3&&col==3)continue;shapes.setColor(row==3?.16f:.08f,row==3?.2f:.15f,row==3?.08f:.24f,1);float x=w*(.49f+col*.125f),y=h*(row==0?.7f:row==1?.51f:row==2?.32f:.13f);shapes.rect(x,y,w*.115f,h*.16f);}shapes.setColor(1f,.65f,.12f,1);shapes.rect(w*.49f,h*.01f,w*.49f,h*.09f);}shapes.end();}
    private void post(float x,float y){shapes.setColor(1,1,1,.75f);shapes.rect(x-.08f,y,.16f,1.8f);shapes.setColor(.95f,.45f,.15f,.9f);shapes.triangle(x,y+1.8f,x,y+2.6f,x+.75f,y+2.2f);}
    private void fill(Vector2[] p){for(int i=0;i<p.length-1;i++){Vector2 a=p[i],b=p[i+1];shapes.triangle(a.x,a.y,b.x,b.y,a.x,-20);shapes.triangle(b.x,b.y,b.x,-20,a.x,-20);}}
    private void line(Vector2[] p){for(int i=0;i<p.length-1;i++)shapes.line(p[i],p[i+1]);}
    private String token(int l){return l>=MAX?l+"/MAX":l+"/"+cost(l);}
    private void drawDesktopHud(){if(Gdx.app.getType()!=com.badlogic.gdx.Application.ApplicationType.Desktop)return;float h=Gdx.graphics.getHeight();hudBatch.setProjectionMatrix(hudProjection);hudBatch.begin();hudFont.setColor(Color.WHITE);hudFont.draw(hudBatch,Math.round(distance())+" m",18,h-18);hudFont.draw(hudBatch,points+" pts\nBest "+Math.round(bestDistance)+" m",Gdx.graphics.getWidth()-180,h-18);if(state==RunState.FINISHED){String result=Math.round(finalDistance)+" m final distance   +"+lastReward+" points   "+(outcome==Outcome.CLEAN?"Clean landing bonus!":"Crash + slide distance!");hudFont.draw(hudBatch,result,18,h-70);hudFont.draw(hudBatch,"SPEED "+token(speedLevel)+"   GLIDE "+token(glideLevel)+"   CONTROL "+token(controlLevel)+"   RAMP "+token(rampLevel)+"\nAERO "+token(aeroLevel)+"   BOUNCE "+token(bounceLevel)+"   SLIDE "+token(slideLevel)+"\nWINGS "+partToken(wingsPart,partCost(0))+"   SUSP "+partToken(suspensionPart,partCost(1))+"   TAIL "+partToken(tailPart,partCost(2))+"   BOOSTER "+partToken(boosterPart,partCost(3))+"\nPress R or SPACE to launch again",18,h-110);}hudBatch.end();}
    private void drawDesktopMenus(){if(Gdx.app.getType()!=com.badlogic.gdx.Application.ApplicationType.Desktop||state==RunState.RUNNING)return;float w=Gdx.graphics.getWidth(),h=Gdx.graphics.getHeight();hudBatch.setProjectionMatrix(hudProjection);hudBatch.begin();hudFont.setColor(Color.WHITE);if(state==RunState.RESULT){hudFont.getData().setScale(2f);hudFont.draw(hudBatch,"RUN COMPLETE",w*.41f,h*.73f);hudFont.getData().setScale(3f);hudFont.draw(hudBatch,Math.round(finalDistance)+" m",w*.43f,h*.59f);hudFont.getData().setScale(2f);hudFont.setColor(1f,.82f,.3f,1);hudFont.draw(hudBatch,"+"+lastReward+" POINTS",w*.4f,h*.45f);hudFont.setColor(.15f,.08f,0,1);hudFont.getData().setScale(1.5f);hudFont.draw(hudBatch,"OPEN UPGRADES",w*.4f,h*.3f);}else{hudFont.getData().setScale(1.35f);hudFont.setColor(Color.WHITE);hudFont.draw(hudBatch,"GEN "+(vehicleType+1)+"  "+generationName(),w*.11f,h*.86f);hudFont.draw(hudBatch,"DEVELOPMENT  "+totalLevels()+" / "+(MAX*7),w*.5f,h*.94f);hudFont.getData().setScale(.72f);String[] names={"SPEED","GLIDE","CONTROL","RAMP","AERO","BOUNCE","BRAKES","","WINGS","GEAR","TAIL","ENGINE","NEXT GENERATION","","",""};String[] values={token(speedLevel),token(glideLevel),token(controlLevel),token(rampLevel),token(aeroLevel),token(bounceLevel),token(slideLevel),"",wingsPart?"FITTED":"DEVELOPING",suspensionPart?"FITTED":"DEVELOPING",tailPart?"FITTED":"DEVELOPING",boosterPart?"FITTED":"DEVELOPING",vehicleType>=MAX_GENERATION?"FINAL MODEL":fullyDeveloped()?"ADVANCE":"FULL UPGRADES NEEDED","","",""};for(int row=0;row<4;row++)for(int col=0;col<4;col++){int i=row*4+col;if(names[i].length()==0)continue;float x=w*(.5f+col*.125f),y=h*(row==0?.82f:row==1?.63f:row==2?.44f:.25f);hudFont.draw(hudBatch,names[i]+"\n"+values[i],x,y);}hudFont.setColor(.15f,.08f,0,1);hudFont.getData().setScale(1.1f);hudFont.draw(hudBatch,"LAUNCH AGAIN",w*.67f,h*.07f);}hudFont.getData().setScale(1.35f);hudBatch.end();}
    private void drawDesktopGold(){if(Gdx.app.getType()!=com.badlogic.gdx.Application.ApplicationType.Desktop||state!=RunState.SHOP)return;float w=Gdx.graphics.getWidth(),h=Gdx.graphics.getHeight();hudBatch.setProjectionMatrix(hudProjection);hudBatch.begin();hudFont.setColor(1f,.82f,.3f,1);hudFont.getData().setScale(1.5f);hudFont.draw(hudBatch,points+" GOLD",w*.83f,h*.93f);hudFont.getData().setScale(1.35f);hudBatch.end();}
    private void title(){String st=state==RunState.RESULT?"RESULT":state==RunState.SHOP?"SHOP":launched?(groundContacts>0?"GROUND":"AIR"):"RAMP";int land=state==RunState.RUNNING?(touchedLanding?Math.round(touchdownDistance):-1):Math.round(finalDistance);String data="FLYEAGLE|DIST="+Math.round(distance())+"|LAND="+land+"|BEST="+Math.round(bestDistance)+"|POINTS="+points+"|REWARD="+lastReward+"|PICKUPS="+pickupPoints+"|SPEED="+token(speedLevel)+"|GLIDE="+token(glideLevel)+"|CONTROL="+token(controlLevel)+"|RAMP="+token(rampLevel)+"|AERO="+token(aeroLevel)+"|BOUNCE="+token(bounceLevel)+"|SLIDE="+token(slideLevel)+"|WINGS="+(wingsPart?"FITTED":"DEVELOPING")+"|SUSP="+(suspensionPart?"FITTED":"DEVELOPING")+"|TAIL="+(tailPart?"FITTED":"DEVELOPING")+"|BOOSTER="+(boosterPart?"FITTED":"DEVELOPING")+"|SLED="+vehicleToken(0)+"|ROCKET="+vehicleToken(1)+"|UFO="+vehicleToken(2)+"|GEN="+(vehicleType+1)+"|MODEL="+generationName()+"|DEV="+totalLevels()+"/"+(MAX*7)+"|CANADVANCE="+(fullyDeveloped()&&vehicleType<MAX_GENERATION)+"|OUTCOME="+outcome.name()+"|STATE="+st;Gdx.graphics.setTitle(data);if(ui!=null)ui.update(data);}
    @Override public void resize(int w,int h){viewport.update(w,h,false);hudProjection.setToOrtho2D(0,0,w,h);if(gameHud!=null)gameHud.resize(w,h);}@Override public void dispose(){if(gameHud!=null)gameHud.dispose();if(hudFont!=null)hudFont.dispose();if(hudBatch!=null)hudBatch.dispose();if(artBatch!=null)artBatch.dispose();if(airshipAnimation!=null)airshipAnimation.dispose();if(skyTexture!=null)skyTexture.dispose();if(cloudTexture!=null)cloudTexture.dispose();if(landscapeTexture!=null)landscapeTexture.dispose();if(iconTexture!=null)iconTexture.dispose();if(propsTexture!=null)propsTexture.dispose();if(fireTexture!=null)fireTexture.dispose();shapes.dispose();world.dispose();}
}
