const AUDIO='assets/audio/normalized';
export class GameAudio{
 constructor({musicVolume=.55,sfxVolume=.8}={}){this.musicVolume=musicVolume;this.sfxVolume=sfxVolume;this.music=new Audio(`${AUDIO}/music/Tin Can Liftoff.mp3`);this.music.loop=true;this.music.preload='metadata';this.music.volume=musicVolume;this.rattle=new Audio(`${AUDIO}/sfx/wheels-on-stone.mp3`);this.rattle.loop=true;this.rattle.preload='metadata';this.engine=new Audio(`${AUDIO}/sfx/Car Engine Loop.wav`);this.engine.loop=true;this.engine.preload='metadata';this.lip=new Audio(`${AUDIO}/sfx/ramp-lip-knock.wav`);this.lip.preload='metadata';this.starts=['Car Engine Start.wav',...Array.from({length:9},(_,i)=>`Car Engine Start_${i+1}.wav`)];this.stops=['Car Engine Stop.wav',...Array.from({length:9},(_,i)=>`Car Engine Stop_${i+1}.wav`)];this.honks=['Car Horn-Honk.wav',...Array.from({length:14},(_,i)=>`Car Horn-Honk_${i+1}.wav`)];this.brakes=[2,3,4].map(i=>`../../sfx/Car Brake Screech_${i}.wav`);this.ready=false;this.nextHonk=Infinity;this.engineStartUntil=0;this.suspended=false}
 async unlock(){if(!this.ctx){const AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AC)return;this.ctx=new AC;this.master=this.ctx.createGain();this.master.gain.value=this.sfxVolume;this.master.connect(this.ctx.destination);this.rattleGain=this.ctx.createGain();this.rattleGain.gain.value=0;this.ctx.createMediaElementSource(this.rattle).connect(this.rattleGain).connect(this.master);this.engineGain=this.ctx.createGain();this.engineGain.gain.value=0;this.ctx.createMediaElementSource(this.engine).connect(this.engineGain).connect(this.master);this.lipGain=this.ctx.createGain();this.lipGain.gain.value=1.8;this.ctx.createMediaElementSource(this.lip).connect(this.lipGain).connect(this.master);this.makeMotionLoops()}this.ready=true;if(this.ctx.state==='suspended')await this.ctx.resume();if(this.musicVolume>0&&this.music.paused)this.music.play().catch(()=>{})}
 setMusic(value){this.musicVolume=value;this.music.volume=value;if(value===0)this.music.pause();else if(this.ready)this.music.play().catch(()=>{})}
 setSfx(value){this.sfxVolume=value;if(this.master)this.master.gain.setTargetAtTime(value,this.ctx.currentTime,.03)}
 setSuspended(hidden){this.suspended=hidden;if(hidden){this.music.pause();this.ctx?.suspend?.()}else if(this.ready){this.ctx?.resume?.().catch(()=>{});if(this.musicVolume>0)this.music.play().catch(()=>{})}}
 makeMotionLoops(){const c=this.ctx,buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;this.wind=c.createBufferSource();this.wind.buffer=buffer;this.wind.loop=true;const filter=c.createBiquadFilter();filter.type='bandpass';filter.frequency.value=900;this.windGain=c.createGain();this.windGain.gain.value=0;this.wind.connect(filter).connect(this.windGain).connect(this.master);this.wind.start();this.rocket=c.createBufferSource();this.rocket.buffer=buffer;this.rocket.loop=true;this.rocketFilter=c.createBiquadFilter();this.rocketFilter.type='lowpass';this.rocketFilter.frequency.value=520;this.rocketFilter.Q.value=1.4;this.rocketGain=c.createGain();this.rocketGain.gain.value=0;this.rocket.connect(this.rocketFilter).connect(this.rocketGain).connect(this.master);this.rocket.start()}
 update(sim){if(!this.ready)return;const t=this.ctx.currentTime,speed=Math.min(1,sim.speed/32),active=['starting','ramp','air'].includes(sim.state),rolling=sim.state==='ramp'||sim.state==='ground';if(sim.boosting&&!this.wasBoosting)this.play('boost');this.wasBoosting=sim.boosting;this.windGain.gain.setTargetAtTime(sim.state==='air'?speed*.11:0,t,.12);this.rocketGain.gain.setTargetAtTime(sim.boosting?.19:0,t,sim.boosting?.025:.045);this.rocketFilter.frequency.setTargetAtTime(420+Math.min(600,sim.speed*3),t,.04);this.rattle.playbackRate=.92+speed;this.rattleGain.gain.setTargetAtTime(rolling?.38+speed:0,t,.06);if(rolling&&this.sfxVolume>0&&this.rattle.paused)this.rattle.play().catch(()=>{});if(!rolling&&!this.rattle.paused){this.rattle.pause();this.rattle.currentTime=0}this.engine.playbackRate=.82+speed*.55;this.engineGain.gain.setTargetAtTime(active&&t>=this.engineStartUntil?.4+speed*.1:0,t,.08);if(active&&t>=this.engineStartUntil&&this.sfxVolume>0&&this.engine.paused)this.engine.play().catch(()=>{});if(!active&&!this.engine.paused){this.engine.pause();this.engine.currentTime=0}if(active&&sim.state!=='starting'&&t>=this.nextHonk){this.playRandom(this.honks,.24);this.nextHonk=t+9+Math.random()*15}}
 tone({from=300,to=500,duration=.15,type='square',gain=.12,delay=0}){if(!this.ready)return;const c=this.ctx,t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(from,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,to),t+duration);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(this.master);o.start(t);o.stop(t+duration+.02)}
 noise(duration=.18,gain=.15,low=300,high=1800){if(!this.ready)return;const c=this.ctx,n=Math.ceil(c.sampleRate*duration),b=c.createBuffer(1,n,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=(low+high)/2;f.Q.value=.8;g.gain.value=gain;s.connect(f).connect(g).connect(this.master);s.start()}
  playRandom(files,volume){if(!this.ready||this.sfxVolume===0)return;const clip=new Audio(`${AUDIO}/sfx/${files[Math.floor(Math.random()*files.length)]}`);clip.volume=Math.min(1,volume*this.sfxVolume);clip.play().catch(()=>{})}
  brake(){this.playRandom(this.brakes,.72)}
  play(name){switch(name){case'boost':this.playRandom(['rocket-ignition-whoosh.mp3'],1);this.playRandom(['rocket-ignition-impact.mp3'],.82);this.noise(.16,.13,70,620);break;case'engineStart':this.engine.pause();this.engine.currentTime=0;this.engineStartUntil=this.ctx.currentTime+.65;this.nextHonk=this.ctx.currentTime+4+Math.random()*7;this.playRandom(this.starts,1);break;case'engineStop':this.engine.pause();this.engine.currentTime=0;this.playRandom(this.stops,1);this.nextHonk=Infinity;break;case'click':this.tone({from:260,to:210,duration:.055,gain:.07});break;case'launch':this.rattle.pause();this.rattle.currentTime=0;this.lip.currentTime=0;this.lip.play().catch(()=>{});this.noise(.22,.1,700,3400);break;case'clean':this.tone({from:440,to:660,duration:.12,gain:.11});this.tone({from:660,to:880,duration:.16,gain:.1,delay:.1});break;case'rough':this.noise(.18,.13,90,650);this.tone({from:130,to:70,duration:.2,type:'triangle',gain:.12});break;case'crash':this.noise(.42,.26,60,800);this.tone({from:110,to:35,duration:.35,type:'sawtooth',gain:.16});break;case'reward':for(let i=0;i<4;i++)this.tone({from:520+i*80,to:620+i*90,duration:.1,gain:.08,delay:i*.065});break;case'buy':this.tone({from:330,to:660,duration:.14,gain:.1});this.tone({from:550,to:990,duration:.18,gain:.08,delay:.1});break}}
}
