export class GameAudio{
 constructor({musicVolume=.55,sfxVolume=.8}={}){this.musicVolume=musicVolume;this.sfxVolume=sfxVolume;this.music=new Audio('assets/audio/music/going-up.ogg');this.music.loop=true;this.music.preload='auto';this.music.volume=musicVolume;this.ready=false}
 async unlock(){if(!this.ctx){const AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AC)return;this.ctx=new AC;this.master=this.ctx.createGain();this.master.gain.value=this.sfxVolume;this.master.connect(this.ctx.destination);this.makeMotionLoops()}if(this.ctx.state==='suspended')await this.ctx.resume();this.ready=true;if(this.musicVolume>0&&this.music.paused)this.music.play().catch(()=>{})}
 setMusic(value){this.musicVolume=value;this.music.volume=value;if(value===0)this.music.pause();else if(this.ready)this.music.play().catch(()=>{})}
 setSfx(value){this.sfxVolume=value;if(this.master)this.master.gain.setTargetAtTime(value,this.ctx.currentTime,.03)}
 makeMotionLoops(){const c=this.ctx;this.roll=c.createOscillator();this.roll.type='square';this.rollGain=c.createGain();this.rollGain.gain.value=0;this.roll.connect(this.rollGain).connect(this.master);this.roll.start();const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;this.wind=c.createBufferSource();this.wind.buffer=buffer;this.wind.loop=true;const filter=c.createBiquadFilter();filter.type='bandpass';filter.frequency.value=900;this.windGain=c.createGain();this.windGain.gain.value=0;this.wind.connect(filter).connect(this.windGain).connect(this.master);this.wind.start()}
 update(sim){if(!this.ready)return;const t=this.ctx.currentTime,speed=Math.min(1,sim.speed/32);this.roll.frequency.setTargetAtTime(34+sim.speed*3.2,t,.04);this.rollGain.gain.setTargetAtTime(sim.state==='ramp'?.025+speed*.035:sim.state==='ground'?.018:0,t,.05);this.windGain.gain.setTargetAtTime(sim.state==='air'?speed*.11:0,t,.12)}
 tone({from=300,to=500,duration=.15,type='square',gain=.12,delay=0}){if(!this.ready)return;const c=this.ctx,t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(from,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,to),t+duration);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(this.master);o.start(t);o.stop(t+duration+.02)}
 noise(duration=.18,gain=.15,low=300,high=1800){if(!this.ready)return;const c=this.ctx,n=Math.ceil(c.sampleRate*duration),b=c.createBuffer(1,n,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=(low+high)/2;f.Q.value=.8;g.gain.value=gain;s.connect(f).connect(g).connect(this.master);s.start()}
 play(name){switch(name){case'click':this.tone({from:260,to:210,duration:.055,gain:.07});break;case'launch':this.noise(.32,.16,400,2200);this.tone({from:180,to:520,duration:.28,type:'sawtooth',gain:.1});break;case'clean':this.tone({from:440,to:660,duration:.12,gain:.11});this.tone({from:660,to:880,duration:.16,gain:.1,delay:.1});break;case'rough':this.noise(.18,.13,90,650);this.tone({from:130,to:70,duration:.2,type:'triangle',gain:.12});break;case'crash':this.noise(.42,.26,60,800);this.tone({from:110,to:35,duration:.35,type:'sawtooth',gain:.16});break;case'reward':for(let i=0;i<4;i++)this.tone({from:520+i*80,to:620+i*90,duration:.1,gain:.08,delay:i*.065});break;case'buy':this.tone({from:330,to:660,duration:.14,gain:.1});this.tone({from:550,to:990,duration:.18,gain:.08,delay:.1});break}}
}
