import{Simulation}from'./simulation.js';import{Renderer}from'./renderer.js';import{GameAudio}from'./audio.js';import{UPGRADES,upgradeCost}from'./config.js';import{scoreRun,purchase}from'./economy.js';import{loadProgress,saveProgress}from'./storage.js';
const $=id=>document.getElementById(id);const canvas=$('game'),renderer=new Renderer(canvas);let progress=loadProgress(),sim=new Simulation(progress.levels),audio=new GameAudio(progress),last=performance.now(),acc=0,awarded=false,previousState=sim.state;
const input={left:false,right:false,boost:false};
function show(id){for(const x of['start','results','shop'])$(x).classList.toggle('hidden',x!==id)}
function start(){audio.unlock().then(()=>audio.play('click'));sim=new Simulation(progress.levels);sim.launch();previousState=sim.state;awarded=false;show('')}
function result(){if(awarded||!sim.result)return;awarded=true;const score=scoreRun(sim.result),oldBest=progress.best;progress={...progress,bolts:progress.bolts+score.total,best:Math.max(progress.best,sim.result.distance),runs:progress.runs+1};saveProgress(progress);audio.play('reward');$('result-distance').textContent=`${Math.floor(sim.result.distance)} m`;$('base-reward').textContent=`+${score.base}`;$('landing-reward').textContent=`+${score.landingBonus}`;$('total-reward').textContent=`+${score.total} bolts`;$('record').textContent=sim.result.distance>oldBest?'NEW SCRAPYARD RECORD!':`${sim.result.landing.toUpperCase()} LANDING`;show('results')}
function shop(){audio.play('click');renderShop();show('shop')}
function renderShop(){$('wallet').textContent=`${progress.bolts} BOLTS`;$('upgrades').replaceChildren(...UPGRADES.map(u=>{const level=progress.levels[u.id],cost=upgradeCost(u,level),el=document.createElement('article');el.className='upgrade';el.innerHTML=`<span class="levels">${'●'.repeat(level)}${'○'.repeat(u.max-level)}</span><h3>${u.name}</h3><p>${u.description}<br><b>${u.effect(level)}</b></p><button ${level>=u.max||progress.bolts<cost?'disabled':''}>${level>=u.max?'MAXED':`BUY · ${cost}`}</button>`;el.querySelector('button').onclick=()=>{const bought=purchase(progress,u.id);if(bought.ok){progress=bought.progress;saveProgress(progress);audio.play('buy');renderShop()}};return el}))}
function setKey(code,on){if(['ArrowLeft','KeyA'].includes(code))input.left=on;if(['ArrowRight','KeyD'].includes(code))input.right=on;if(code==='Space')input.boost=on}
addEventListener('keydown',e=>{setKey(e.code,true);if(e.repeat)return;if(e.code==='Space'){e.preventDefault();if(!$('start').classList.contains('hidden'))start();else if(!$('results').classList.contains('hidden'))start();else if(!$('shop').classList.contains('hidden'))start()}if(e.code==='KeyR')start()});addEventListener('keyup',e=>setKey(e.code,false));
canvas.addEventListener('pointerdown',e=>{if(sim.state==='air'){input[e.clientX<innerWidth/2?'left':'right']=true}});canvas.addEventListener('pointerup',()=>{input.left=input.right=false});
$('launch').onclick=start;$('retry').onclick=start;$('open-shop').onclick=shop;$('shop-launch').onclick=start;$('motion').onclick=()=>{audio.play('click');progress={...progress,reducedMotion:!progress.reducedMotion};saveProgress(progress);updateControls()};
const nextVolume=(current,steps)=>steps[(steps.findIndex(v=>Math.abs(v-current)<.01)+1)%steps.length];
$('music').onclick=()=>{audio.unlock();progress={...progress,musicVolume:nextVolume(progress.musicVolume,[.55,.25,0])};audio.setMusic(progress.musicVolume);saveProgress(progress);updateControls()};
$('sfx').onclick=()=>{audio.unlock().then(()=>audio.play('click'));progress={...progress,sfxVolume:nextVolume(progress.sfxVolume,[.8,.4,0])};audio.setSfx(progress.sfxVolume);saveProgress(progress);updateControls()};
function updateControls(){$('motion').textContent=`FX: ${progress.reducedMotion?'CALM':'FULL'}`;$('motion').setAttribute('aria-pressed',String(progress.reducedMotion));$('music').textContent=`MUSIC: ${Math.round(progress.musicVolume*100)}%`;$('sfx').textContent=`SFX: ${Math.round(progress.sfxVolume*100)}%`}updateControls();
addEventListener('resize',()=>renderer.resize());document.addEventListener('visibilitychange',()=>{last=performance.now();acc=0});
function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(document.visibilityState==='visible'){acc+=dt;while(acc>=1/60){sim.step(input,1/60);acc-=1/60}if(previousState==='ramp'&&sim.state==='air')audio.play('launch');if(previousState==='air'&&sim.state==='ground')audio.play(sim.landing);previousState=sim.state;if(sim.state==='complete')result();audio.update(sim);renderer.draw(sim,progress.reducedMotion,now);$('distance').textContent=`${Math.floor(Math.max(0,sim.maxDistance))} m`;$('speed').textContent=`${Math.round(sim.speed*3.6)} km/h`;$('state').textContent=sim.state.toUpperCase();$('best').textContent=`BEST ${Math.floor(progress.best)} m`}requestAnimationFrame(frame)}requestAnimationFrame(frame);
