import{PALETTE as C}from'./config.js';import{groundAt,RAMP_END}from'./simulation.js';
const lerp=(a,b,t)=>a+(b-a)*t;
export class Renderer{constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.camera={x:-57,y:54,shake:0};this.dpr=1;this.resize()}resize(){this.dpr=Math.min(2,devicePixelRatio||1);this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;this.canvas.width=this.w*this.dpr;this.canvas.height=this.h*this.dpr;this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0)}
 draw(sim,reduced=false,time=0){const g=this.ctx,w=this.w,h=this.h,scale=Math.max(10,Math.min(18,w/82));const ready=sim.state==='ready';const targetX=ready?sim.x+7:sim.x+10;const targetY=ready?sim.y-9:Math.max(8,sim.y+2);this.camera.x=lerp(this.camera.x,targetX,.055);this.camera.y=lerp(this.camera.y,targetY,.04);const shake=!reduced&&sim.state==='ground'&&sim.landing==='crash'?Math.sin(time*.08)*2:0;const sx=x=>(x-this.camera.x)*scale+w*.42+shake,sy=y=>h*.68-(y-this.camera.y)*scale;g.fillStyle=C.sky;g.fillRect(0,0,w,h);g.fillStyle=C.sun;g.beginPath();g.arc(w*.77,h*.2,55,0,Math.PI*2);g.fill();
 this.hills(g,w,h,this.camera.x,scale,.12,h*.49,34,260,C.skyDark);this.hills(g,w,h,this.camera.x,scale,.28,h*.56,46,205,C.moss);this.roadside(g,w,this.camera.x,scale,sy);
 g.fillStyle=C.grass;g.beginPath();g.moveTo(0,h);for(let px=0;px<=w+20;px+=20){const wx=this.camera.x+(px-w*.42)/scale;g.lineTo(px,sy(groundAt(wx)))}g.lineTo(w,h);g.fill();
 g.strokeStyle=C.ink;g.lineWidth=4;g.beginPath();for(let x=this.camera.x-w/scale;x<this.camera.x+w/scale;x+=.35){const px=sx(x),py=sy(groundAt(x));if(x===this.camera.x-w/scale)g.moveTo(px,py);else g.lineTo(px,py)}g.stroke();this.landingRoad(g,sx,sy,scale,w);
 this.cloud(g,this.wrap(w*.15-this.camera.x*scale*.18,w+220)-110,h*.18,1);this.cloud(g,this.wrap(w*.72-this.camera.x*scale*.09,w+300)-100,h*.31,.7);this.vehicle(g,sx(sim.x),sy(sim.y),sim.angle,sim, time);if(sim.state==='air'&&sim.boost>0)for(let i=0;i<4;i++){g.fillStyle=i%2?C.gold:C.cream;g.fillRect(sx(sim.x)-Math.cos(sim.angle)*45-i*7,sy(sim.y)+Math.sin(sim.angle)*45+(i%2)*4,8,5)} }
 wrap(value,size){return((value%size)+size)%size}
 hills(g,w,h,cameraX,scale,factor,base,amplitude,period,color){const shift=cameraX*scale*factor;g.fillStyle=color;g.beginPath();g.moveTo(0,h);for(let px=-20;px<=w+20;px+=12){const p=(px+shift)/period;const ridge=Math.sin(p*Math.PI*2)*.55+Math.sin(p*Math.PI*4+1.7)*.22+Math.sin(p*Math.PI+2.4)*.23;g.lineTo(px,base-ridge*amplitude)}g.lineTo(w,h);g.fill()}
 roadside(g,w,cameraX,scale,sy){const repeat=92,clusters=[4,8.5,14,34,39,44.5,50,73,79],left=cameraX-w*.5/scale,right=cameraX+w*.7/scale,start=Math.floor(left/repeat)*repeat;for(let base=start;base<=right+repeat;base+=repeat)for(let j=0;j<clusters.length;j++){const wx=base+clusters[j];if(wx<RAMP_END+5||wx<left||wx>right)continue;const x=(wx-cameraX)*scale+w*.42,y=sy(groundAt(wx)),variant=(Math.abs(Math.round(base))+j*7)%4,s=.52+variant*.065;g.fillStyle=C.coal;g.fillRect(x-3*s,y-38*s,6*s,40*s);g.strokeStyle=C.ink;g.lineWidth=2.5;g.fillStyle=C.moss;g.beginPath();g.moveTo(x-25*s,y-27*s);g.lineTo(x,y-77*s);g.lineTo(x+26*s,y-27*s);g.closePath();g.fill();g.stroke()}}
 landingRoad(g,sx,sy,scale,w){const left=Math.max(RAMP_END,this.camera.x-w/scale),right=this.camera.x+w/scale;const path=()=>{g.beginPath();for(let x=left;x<=right+.4;x+=.35){const px=sx(x),py=sy(groundAt(x));if(x===left)g.moveTo(px,py);else g.lineTo(px,py)}};g.lineJoin='round';g.lineCap='round';path();g.strokeStyle=C.coal;g.lineWidth=18;g.stroke();path();g.strokeStyle=C.iron;g.lineWidth=11;g.stroke();path();g.strokeStyle=C.paper;g.lineWidth=2;g.setLineDash([12,18]);g.stroke();g.setLineDash([]);g.lineCap='butt';g.lineJoin='miter'}
 cloud(g,x,y,s){g.fillStyle=C.cloud;g.strokeStyle=C.ink;g.lineWidth=3;g.beginPath();g.arc(x,y,28*s,Math.PI,0);g.arc(x+32*s,y-8*s,35*s,Math.PI,0);g.arc(x+70*s,y,25*s,Math.PI,0);g.lineTo(x+70*s,y+14*s);g.lineTo(x,y+14*s);g.closePath();g.fill();g.stroke()}
 vehicle(g,x,y,a,sim,t){g.save();g.translate(x,y);g.rotate(-a);const rattle=sim.state==='ramp'?Math.sin(t*.025)*2:0;g.translate(0,rattle);g.strokeStyle=C.ink;g.lineWidth=4;g.fillStyle=C.rust;g.beginPath();g.moveTo(-34,-10);g.lineTo(30,-10);g.lineTo(24,11);g.lineTo(-28,13);g.closePath();g.fill();g.stroke();g.fillStyle=C.paper;g.fillRect(-22,-20,16,10);g.strokeRect(-22,-20,16,10);g.fillStyle=C.iron;g.fillRect(20,-17,8,7);g.strokeRect(20,-17,8,7);g.fillStyle=C.coal;for(const wx of[-22,20]){g.beginPath();g.arc(wx,16,9,0,Math.PI*2);g.fill();g.stroke();g.fillStyle=C.ash;g.beginPath();g.arc(wx,16,3,0,Math.PI*2);g.fill();g.fillStyle=C.coal}if((sim.levels.aero||0)>0){g.fillStyle=C.paper;g.beginPath();g.moveTo(-2,-5);g.lineTo(18,-36);g.lineTo(29,-34);g.lineTo(13,-4);g.fill();g.stroke()}if((sim.levels.boost||0)>0){g.fillStyle=C.iron;g.fillRect(-44,-5,12,10);g.strokeRect(-44,-5,12,10)}g.restore()}}
