import{PALETTE as C}from'./config.js';import{groundAt,RAMP_END}from'./simulation.js';
const lerp=(a,b,t)=>a+(b-a)*t;
export class Renderer{constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.camera={x:-57,y:54,shake:0};this.dpr=1;this.resize()}resize(){this.dpr=Math.min(2,devicePixelRatio||1);this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;this.canvas.width=this.w*this.dpr;this.canvas.height=this.h*this.dpr;this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0)}
 draw(sim,reduced=false,time=0){const g=this.ctx,w=this.w,h=this.h,scale=Math.max(10,Math.min(18,w/82));const ready=sim.state==='ready';const targetX=ready?sim.x+7:sim.x+10;const targetY=ready?sim.y-9:Math.max(8,sim.y+2);this.camera.x=lerp(this.camera.x,targetX,.055);this.camera.y=lerp(this.camera.y,targetY,.04);const shake=!reduced&&sim.state==='ground'&&sim.landing==='crash'?Math.sin(time*.08)*2:0;const sx=x=>(x-this.camera.x)*scale+w*.42+shake,sy=y=>h*.68-(y-this.camera.y)*scale;g.fillStyle=C.sky;g.fillRect(0,0,w,h);g.fillStyle=C.sun;g.beginPath();g.arc(w*.77,h*.2,55,0,Math.PI*2);g.fill();
 this.hills(g,w,h,this.camera.x,scale,.12,h*.49,34,260,C.skyDark);this.hills(g,w,h,this.camera.x,scale,.28,h*.56,46,205,C.moss);this.roadside(g,w,this.camera.x,scale,sy);
 g.fillStyle=C.grass;g.beginPath();g.moveTo(0,h);for(let px=0;px<=w+20;px+=20){const wx=this.camera.x+(px-w*.42)/scale;g.lineTo(px,sy(groundAt(wx,sim.facilities?.ramp||0)))}g.lineTo(w,h);g.fill();
 g.strokeStyle=C.ink;g.lineWidth=4;g.beginPath();for(let x=this.camera.x-w/scale;x<this.camera.x+w/scale;x+=.35){const px=sx(x),py=sy(groundAt(x,sim.facilities?.ramp||0));if(x===this.camera.x-w/scale)g.moveTo(px,py);else g.lineTo(px,py)}g.stroke();this.launchFacility(g,sx,sy,sim.facilities?.ramp||0);this.landingRoad(g,sx,sy,scale,w);
 this.cloud(g,this.wrap(w*.15-this.camera.x*scale*.18,w+220)-110,h*.18,1);this.cloud(g,this.wrap(w*.72-this.camera.x*scale*.09,w+300)-100,h*.31,.7);this.vehicle(g,sx(sim.x),sy(sim.y),sim.angle,sim, time);if(sim.state==='air'&&sim.boost>0)for(let i=0;i<4;i++){g.fillStyle=i%2?C.gold:C.cream;g.fillRect(sx(sim.x)-Math.cos(sim.angle)*45-i*7,sy(sim.y)+Math.sin(sim.angle)*45+(i%2)*4,8,5)} }
 wrap(value,size){return((value%size)+size)%size}
 hills(g,w,h,cameraX,scale,factor,base,amplitude,period,color){const shift=cameraX*scale*factor;g.fillStyle=color;g.beginPath();g.moveTo(0,h);for(let px=-20;px<=w+20;px+=12){const p=(px+shift)/period;const ridge=Math.sin(p*Math.PI*2)*.55+Math.sin(p*Math.PI*4+1.7)*.22+Math.sin(p*Math.PI+2.4)*.23;g.lineTo(px,base-ridge*amplitude)}g.lineTo(w,h);g.fill()}
 launchFacility(g,sx,sy,level){if(level<1)return;g.save();g.strokeStyle=level>=5?C.gold:C.iron;g.lineWidth=3+Math.min(3,level*.5);for(let x=-14;x<=12;x+=6){const top=groundAt(x,level),base=groundAt(x,0)-2;g.beginPath();g.moveTo(sx(x),sy(top));g.lineTo(sx(x-2),sy(base));g.lineTo(sx(x+2),sy(base));g.closePath();g.stroke()}g.strokeStyle=level>=4?C.gold:C.paper;g.lineWidth=2+level*.55;g.beginPath();for(let x=-17;x<RAMP_END;x+=.4){const px=sx(x),py=sy(groundAt(x,level)-.45);if(x===-17)g.moveTo(px,py);else g.lineTo(px,py)}g.stroke();if(level>=5){g.strokeStyle=C.gold;g.lineWidth=3;for(let i=0;i<level-3;i++){g.beginPath();g.arc(sx(RAMP_END+1),sy(groundAt(RAMP_END-.01,level)-1),14+i*9,0,Math.PI*2);g.stroke()}}g.restore()}
 roadside(g,w,cameraX,scale,sy){const repeat=92,clusters=[4,8.5,14,34,39,44.5,50,73,79],left=cameraX-w*.5/scale,right=cameraX+w*.7/scale,start=Math.floor(left/repeat)*repeat;for(let base=start;base<=right+repeat;base+=repeat)for(let j=0;j<clusters.length;j++){const wx=base+clusters[j];if(wx<RAMP_END+5||wx<left||wx>right)continue;const x=(wx-cameraX)*scale+w*.42,y=sy(groundAt(wx)),variant=(Math.abs(Math.round(base))+j*7)%4,s=.52+variant*.065;g.fillStyle=C.coal;g.fillRect(x-3*s,y-38*s,6*s,40*s);g.strokeStyle=C.ink;g.lineWidth=2.5;g.fillStyle=C.moss;g.beginPath();g.moveTo(x-25*s,y-27*s);g.lineTo(x,y-77*s);g.lineTo(x+26*s,y-27*s);g.closePath();g.fill();g.stroke()}}
 landingRoad(g,sx,sy,scale,w){const left=Math.max(RAMP_END,this.camera.x-w/scale),right=this.camera.x+w/scale;const path=()=>{g.beginPath();for(let x=left;x<=right+.4;x+=.35){const px=sx(x),py=sy(groundAt(x));if(x===left)g.moveTo(px,py);else g.lineTo(px,py)}};g.lineJoin='round';g.lineCap='round';path();g.strokeStyle=C.coal;g.lineWidth=18;g.stroke();path();g.strokeStyle=C.iron;g.lineWidth=11;g.stroke();path();g.strokeStyle=C.paper;g.lineWidth=2;g.setLineDash([12,18]);g.stroke();g.setLineDash([]);g.lineCap='butt';g.lineJoin='miter'}
 cloud(g,x,y,s){g.fillStyle=C.cloud;g.strokeStyle=C.ink;g.lineWidth=3;g.beginPath();g.arc(x,y,28*s,Math.PI,0);g.arc(x+32*s,y-8*s,35*s,Math.PI,0);g.arc(x+70*s,y,25*s,Math.PI,0);g.lineTo(x+70*s,y+14*s);g.lineTo(x,y+14*s);g.closePath();g.fill();g.stroke()}
 preview(canvas,levels,parts,vehicle,time=0){const dpr=Math.min(2,devicePixelRatio||1),w=canvas.clientWidth,h=canvas.clientHeight,large=canvas.id==='vehicle-preview',zoom=large?1.45:1;canvas.width=w*dpr;canvas.height=h*dpr;const g=canvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);g.save();g.translate(w*.5,h*.55);g.scale(zoom,zoom);this.vehicle(g,0,0,0,{state:'ready',levels,parts,vehicle},time);g.restore()}
 partPreview(canvas,partId,vehicle,time=0){this.preview(canvas,{}, {[partId]:true},vehicle,time)}
 vehicle(g,x,y,a,sim,t){g.save();g.translate(x,y);g.rotate(-a);const rattle=sim.state==='ramp'?Math.sin(t*.025)*2:0,parts=sim.parts||{},model=sim.vehicle?.id||'cart';g.translate(0,rattle);g.strokeStyle=C.ink;g.lineWidth=4;
  if(parts.tailwing){g.fillStyle=C.moss;g.fillRect(-47,-31,7,34);g.strokeRect(-47,-31,7,34);g.beginPath();g.moveTo(-58,-35);g.lineTo(-28,-35);g.lineTo(-32,-25);g.lineTo(-55,-25);g.closePath();g.fill();g.stroke()}
  if(parts.rocketpack){for(const ry of[-17,-4]){g.fillStyle=C.gold;g.fillRect(-49,ry,18,10);g.strokeRect(-49,ry,18,10);g.fillStyle=C.rustDark;g.fillRect(-54,ry+2,5,6)}}
  if(model==='bathtub'){g.fillStyle=C.cream;g.beginPath();g.moveTo(-39,-14);g.bezierCurveTo(-35,14,-24,15,20,13);g.bezierCurveTo(35,11,39,-2,38,-14);g.closePath();g.fill();g.stroke();g.strokeStyle=C.rust;g.lineWidth=7;g.beginPath();g.moveTo(-40,-14);g.lineTo(39,-14);g.stroke();g.strokeStyle=C.ink;g.lineWidth=4;g.beginPath();g.moveTo(24,-14);g.lineTo(24,-30);g.quadraticCurveTo(24,-37,32,-37);g.lineTo(37,-37);g.stroke();g.fillStyle=C.skyDark;g.fillRect(-17,-26,20,12);g.strokeRect(-17,-26,20,12)}else if(model==='coffin'){g.fillStyle=C.coal;g.beginPath();g.moveTo(-43,-9);g.lineTo(-27,-20);g.lineTo(22,-17);g.lineTo(45,0);g.lineTo(23,13);g.lineTo(-31,13);g.closePath();g.fill();g.stroke();g.fillStyle=C.rust;g.fillRect(-39,-5,13,13);g.strokeRect(-39,-5,13,13);g.fillStyle=C.gold;g.beginPath();g.moveTo(43,-1);g.lineTo(55,2);g.lineTo(43,7);g.closePath();g.fill();g.stroke();g.fillStyle=C.sky;g.beginPath();g.arc(5,-16,10,Math.PI,0);g.fill();g.stroke()}else if(model==='scrapstar'){g.fillStyle=C.iron;g.beginPath();g.ellipse(0,0,47,17,0,0,Math.PI*2);g.fill();g.stroke();g.fillStyle=C.gold;g.beginPath();g.ellipse(0,2,34,8,0,0,Math.PI);g.fill();g.stroke();g.fillStyle=C.sky;g.beginPath();g.arc(0,-7,20,Math.PI,0);g.closePath();g.fill();g.stroke();g.strokeStyle=C.rust;g.lineWidth=4;g.beginPath();g.moveTo(0,-27);g.lineTo(0,-39);g.stroke();g.fillStyle=C.gold;g.beginPath();g.arc(0,-42,4,0,Math.PI*2);g.fill();g.stroke()}else{g.fillStyle=C.rust;g.beginPath();g.moveTo(-34,-10);g.lineTo(30,-10);g.lineTo(24,11);g.lineTo(-28,13);g.closePath();g.fill();g.stroke();g.fillStyle=C.paper;g.fillRect(-22,-20,16,10);g.strokeRect(-22,-20,16,10);g.fillStyle=C.iron;g.fillRect(20,-17,8,7);g.strokeRect(20,-17,8,7)}
  if(parts.cage){g.strokeStyle=C.gold;g.lineWidth=6;g.beginPath();g.moveTo(-25,-8);g.lineTo(-22,-31);g.lineTo(7,-31);g.lineTo(15,-8);g.moveTo(-21,-30);g.lineTo(12,-8);g.stroke();g.strokeStyle=C.ink;g.lineWidth=2;g.beginPath();g.moveTo(-25,-8);g.lineTo(-22,-31);g.lineTo(7,-31);g.lineTo(15,-8);g.stroke()}
  if(parts.nose){g.fillStyle=C.cream;g.beginPath();g.moveTo(27,-11);g.lineTo(49,2);g.lineTo(24,11);g.closePath();g.fill();g.stroke()}
  g.fillStyle=C.coal;g.strokeStyle=C.ink;g.lineWidth=4;for(const wx of[-22,20]){g.beginPath();g.arc(wx,16,9,0,Math.PI*2);g.fill();g.stroke();g.fillStyle=C.ash;g.beginPath();g.arc(wx,16,3,0,Math.PI*2);g.fill();g.fillStyle=C.coal}
  if((sim.levels.aero||0)>0){g.fillStyle=C.paper;g.beginPath();g.moveTo(-2,-5);g.lineTo(18,-36);g.lineTo(29,-34);g.lineTo(13,-4);g.fill();g.stroke()}if((sim.levels.boost||0)>0){g.fillStyle=C.iron;g.fillRect(-44,-5,12,10);g.strokeRect(-44,-5,12,10)}g.restore()}}
