import{PALETTE as C}from'./config.js';import{groundAt}from'./simulation.js';
const lerp=(a,b,t)=>a+(b-a)*t;
export class Renderer{constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.camera={x:-10,y:9,shake:0};this.dpr=1;this.resize()}resize(){this.dpr=Math.min(2,devicePixelRatio||1);this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;this.canvas.width=this.w*this.dpr;this.canvas.height=this.h*this.dpr;this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0)}
 draw(sim,reduced=false,time=0){const g=this.ctx,w=this.w,h=this.h,scale=Math.max(14,Math.min(24,w/65));const targetX=sim.state==='ready'?-11:sim.x+10;const targetY=Math.max(8,sim.y+2);this.camera.x=lerp(this.camera.x,targetX,.055);this.camera.y=lerp(this.camera.y,targetY,.04);const shake=!reduced&&sim.state==='ground'&&sim.landing==='crash'?Math.sin(time*.08)*2:0;const sx=x=>(x-this.camera.x)*scale+w*.42+shake,sy=y=>h*.68-(y-this.camera.y)*scale;g.fillStyle=C.sky;g.fillRect(0,0,w,h);g.fillStyle=C.sun;g.beginPath();g.arc(w*.77,h*.2,55,0,Math.PI*2);g.fill();
 for(let layer=0;layer<3;layer++){g.fillStyle=[C.skyDark,C.moss,C.grass][layer];g.beginPath();g.moveTo(0,h);for(let px=0;px<=w+20;px+=20){const wx=this.camera.x+(px-w*.42)/scale;const yy=layer===2?groundAt(wx):(-1-layer*2+Math.sin(wx*(.018+layer*.005))*2.2);g.lineTo(px,sy(yy)+layer*22)}g.lineTo(w,h);g.fill()}
 g.strokeStyle=C.ink;g.lineWidth=4;g.beginPath();for(let x=this.camera.x-w/scale;x<this.camera.x+w/scale;x+=.35){const px=sx(x),py=sy(groundAt(x));if(x===this.camera.x-w/scale)g.moveTo(px,py);else g.lineTo(px,py)}g.stroke();
 this.cloud(g,w*.15-(this.camera.x*.8)% (w+180),h*.18,1);this.cloud(g,w*.72-(this.camera.x*.35)% (w+250),h*.31,.7);this.vehicle(g,sx(sim.x),sy(sim.y),sim.angle,sim, time);if(sim.state==='air'&&sim.boost>0)for(let i=0;i<4;i++){g.fillStyle=i%2?C.gold:C.cream;g.fillRect(sx(sim.x)-Math.cos(sim.angle)*45-i*7,sy(sim.y)+Math.sin(sim.angle)*45+(i%2)*4,8,5)} }
 cloud(g,x,y,s){g.fillStyle=C.cloud;g.strokeStyle=C.ink;g.lineWidth=3;g.beginPath();g.arc(x,y,28*s,Math.PI,0);g.arc(x+32*s,y-8*s,35*s,Math.PI,0);g.arc(x+70*s,y,25*s,Math.PI,0);g.lineTo(x+70*s,y+14*s);g.lineTo(x,y+14*s);g.closePath();g.fill();g.stroke()}
 vehicle(g,x,y,a,sim,t){g.save();g.translate(x,y);g.rotate(a);const rattle=sim.state==='ramp'?Math.sin(t*.025)*2:0;g.translate(0,rattle);g.strokeStyle=C.ink;g.lineWidth=4;g.fillStyle=C.rust;g.beginPath();g.moveTo(-34,-10);g.lineTo(30,-10);g.lineTo(24,11);g.lineTo(-28,13);g.closePath();g.fill();g.stroke();g.fillStyle=C.paper;g.fillRect(-22,-20,16,10);g.strokeRect(-22,-20,16,10);g.fillStyle=C.iron;g.fillRect(20,-17,8,7);g.strokeRect(20,-17,8,7);g.fillStyle=C.coal;for(const wx of[-22,20]){g.beginPath();g.arc(wx,16,9,0,Math.PI*2);g.fill();g.stroke();g.fillStyle=C.ash;g.beginPath();g.arc(wx,16,3,0,Math.PI*2);g.fill();g.fillStyle=C.coal}if((sim.levels.aero||0)>0){g.fillStyle=C.paper;g.beginPath();g.moveTo(-2,-5);g.lineTo(18,-36);g.lineTo(29,-34);g.lineTo(13,-4);g.fill();g.stroke()}if((sim.levels.boost||0)>0){g.fillStyle=C.iron;g.fillRect(-44,-5,12,10);g.strokeRect(-44,-5,12,10)}g.restore()}}
